### ISSUE TITLE
Notifications on lock screen

### ISSUE THREAD

**Issue by simonbcn** [RaphaelRochet/arch-update#117]
```
GNOME Shell 3.28.3
Arch-update v27
```

Gnome extensions are supposed to be disabled when the screen is idle. In addition, I have disabled the general setting of not displaying notifications on the lock screen. 
But since recently this indicator is notifying me on the lock screen of new updates. 

On the other hand, I've checked the system log and I get [a lot of meaningless lines](https://pastebin.com/2N0jcLQE) from this extension: 6729 lines since yesterday!
I don't know if there's any connection

**Comment by simonbcn** [comment]
I don't know where the problem was but now it works well.

**Comment by simonbcn** [comment]
No, it fails again:
```
...
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:334 (0x7fc5ebf30918 @ 836)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c60 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:350 (0x7fc5ebf30a28 @ 65)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:335 (0x7fc5ebf30918 @ 870)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c60 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:351 (0x7fc5ebf30a28 @ 88)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:335 (0x7fc5ebf30918 @ 870)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c60 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:352 (0x7fc5ebf30a28 @ 118)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:335 (0x7fc5ebf30918 @ 870)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c60 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:353 (0x7fc5ebf30a28 @ 137)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:335 (0x7fc5ebf30918 @ 870)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c60 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:357 (0x7fc5ebf30a28 @ 161)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:335 (0x7fc5ebf30918 @ 870)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:235 (0x7fc5ebf30560 @ 82)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:341 (0x7fc5ebf30918 @ 931)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #0 0x7ffea9d06c90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:237 (0x7fc5ebf30560 @ 103)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #2 0x7ffea9d06d90 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:341 (0x7fc5ebf30918 @ 931)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #4 0x7ffea9d06ea0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:422 (0x7fc5ebf30d58 @ 126)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #6 0x7ffea9d06fb0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:410 (0x7fc5ebf30c48 @ 285)
ago 06 11:37:26 arch-juan org.gnome.Shell.desktop[717]: #8 0x7ffea9d070b0 b   /home/juan/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:377 (0x7fc5ebf30b38 @ 17)
...
```

I have to disable this extension until this works well.

**Comment by RaphaelRochet** [comment]
Ok I'll investigate.

**Comment by simonbcn** [comment]
There are 2 problems, I don't know if they are related.

1. Notifications on lock screen.
2. Too many errors/warnings in journal.

Could the second problem be caused by using this line: `/bin/sh -c "yay -Sy &>/dev/null && yay -Pu --color never"` to check for updates?

**Comment by RaphaelRochet** [comment]
Do you see errors even when the screen is not locked ?

I think there's something about timers not being disabled while screen is locked. I noticed the extension is disabled but not completely unloaded, letting active timers trigger orphaned code. I didn't took the time to look at it yet.

**Comment by simonbcn** [comment]
I didn't realize that, logging errors only occur while the session is idle.

**Comment by RaphaelRochet** [comment]
I have fix the errors you see in logs. But I can't reproduce your first issue, the notifications on lock screen : every time I lock my screen, the extensions is correctly disabled and can't do anything.
Do you have transient notifications enabled ?

**Comment by simonbcn** [comment]
Yes, I have transient notifications enabled. The notification on lock screen occurs sometimes.
Today it haven't occurred.

**Comment by RaphaelRochet** [comment]
Ahhh could it be "old" (already fired)  notifications that are shown then ... I don't think I can do something for that .... or ... maybe ... I can delete them on destroy .. *intense thinking*

**Comment by RaphaelRochet** [comment]
Can you try the latest commit ? Should fix the notification issue.

**Comment by RaphaelRochet** [comment]
I made a little fix on the fix to suppress a bug introduced with the fix. Can you give it a try ?

**Comment by simonbcn** [comment]
I'm testing it.

**Comment by simonbcn** [comment]
The error no longer appears in my log. But notifications still appear when the display is off. Extensions are supposed to be disabled when the session is idle.

**Comment by RaphaelRochet** [comment]
I have no clue where to look now. 
On my setup the extension is completely disabled whenever I lock the screen, all timers and triggers are stopped (ie the extension won"t check for updates neither it will detect a change in pacman cache) and any existing notification is removed.

**Comment by simonbcn** [comment]
Is there any way to debug it?

**Comment by RaphaelRochet** [comment]
There's no debugger, only thing one can add is add log commands in extension.js to see if/when such or such function is called, or output some variables in the log.
For exemple, adding :
```log("arch-update is stopping");```
just after :
```	destroy: function() {```
will let you see in the log "arch-update is stopping" each time the extension is disabled.

**Comment by simonbcn** [comment]
I'm going to close this issue. I'm not sure it's an extension problem. It doesn't always happen. In fact, in the last 4 days it hasn't happened again.
